### PR TITLE
Run Localstack on Kubernetes for testing

### PR DESCRIPTION
**Pull request by mhmxs**
### Description of your changes

With Docker compose the test execution was a bit faster, but the configuration had hard coded IPs which should be different on different environments. With this change Localstack runs on Kubernetes :)

I have:

- [X] Read and followed Crossplane's [contribution process].
- [X] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### How has this code been tested

E2E tests are green.

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

**Review by nolancon — CHANGES_REQUESTED** [review]
This breaks the `make dev` target which is useful for development. I tried fixing it by applying the localstack deployment, but I still had issues contacting the backends so I'm obviously missing something. Could we get this fixed before merging :pray:

**Comment by mhmxs** [comment]
> This breaks the `make dev` target which is useful for development. I tried fixing it by applying the localstack deployment, but I still had issues contacting the backends so I'm obviously missing something. Could we get this fixed before merging 🙏

@nolancon I'm glad to fix it, but the way how `dev` works won't work well once we merge the webhook change. My suggestion is to remove `dev` and introduce [mirrord](https://github.com/metalbear-co/mirrord) for local development. WDYT?

**Comment by nolancon** [comment]
> > This breaks the `make dev` target which is useful for development. I tried fixing it by applying the localstack deployment, but I still had issues contacting the backends so I'm obviously missing something. Could we get this fixed before merging 🙏
> 
> @nolancon I'm glad to fix it, but the way how `dev` works won't work well once we merge the webhook change. My suggestion is to remove `dev` and introduce [mirrord](https://github.com/metalbear-co/mirrord) for local development. WDYT?

Fair point. I haven't had time to try out mirrord yet but I'm open to seeing what it is like. 
I would say either: 
1)  Fix the existing `make dev` in this PR and we can implement mirrord later.
or
2) Introduce mirrord as part of this PR for local dev.

I just don't want to be left with a broken dev environment on main :pray:

**Comment by mhmxs** [comment]
> I just don't want to be left with a broken dev environment on main

Mirrord has some difficulties, so i did both. As an experimental i start using it, and would like to to fix mirrord.

**Review by nolancon — APPROVED** [review]

**Pull request merged**
